# Generated by Django 2.2.15 on 2022-07-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220727_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.SmallIntegerField(null=True, unique=True),
        ),
    ]
